### ISSUE TITLE
Add fixed-header to table on TableDetail view

### ISSUE THREAD

**Issue by jtomeck** [multinet-app/multinet#245]
`fixed-header` prop is not working on `v-data-table`

**Comment by waxlamp** [comment]
It turns out you need to set a `height` on the table in order for `fixed-header` to work. Here's a [codepen](https://codepen.io/aichoudh/pen/ZEYxowm) illustrating that. I also tried `"100vh"` for the height value and I think that worked as well. We probably need to play around to figure out the right way to do this for TableDetail.

**Comment by jtomeck** [comment]
@waxlamp 

It appears that adding `height="calc( 100vh - 123px )"` to our table works. The 123px comes from the height of the app-bar and the header of the table combined (64px + 59px).

**Comment by waxlamp** [comment]
Great! Feel free to open a PR with this change and let's see how it looks.
