### ISSUE TITLE
Create Sample Views on the Landing Page

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet#274]
We want to show shortcuts with screenshots of demo applications and datasets on the landing page.

Something like this: 

![image](https://user-images.githubusercontent.com/2039375/73493016-1c183200-436f-11ea-8875-73c48671f8b3.png)
https://taggle.caleydoapp.org/

Doesn't have to be a fancy carousel though. 

We could call them "featured project" and use that down the line to feature new dataset.

**Comment by jtomeck** [comment]
We have another application that has a screen full of sample data to use if you don't have your own to upload: https://kitware.github.io/paraview-glance/app/

Does the grid view shown here seem like an acceptable solution? The carousel is visually appealing, but I think it adds more work for the user to find what they're looking for, as most of their options aren't visible.

**Comment by waxlamp** [comment]
@alexsb, can you provide some examples of what you might expect to see in the Multinet app? I assume things like Graffinity and Juniper, perhaps linked with example data so that clicking on it goes either to the network view for that dataset, or directly to the appropriate vis app?

If that's right, then we need a bit of guidance: right now, we just have the node-link diagram and the adjacency matrix views. We can set those up as the options on the landing page, but it's not clear to me what clicking on them should do. Can you give us some ideas there?

**Comment by alexsb** [comment]
I think the grid is a fine solution. 

I would only want to show what is currently available in multinet, so right now that would be a bit boring, but that's OK, I'm sure the ParaView example didn't look much better 1 year in :).

**Comment by alexsb** [comment]
And clicking them should actually load the view with this dataset, just like in paraview.
